### ISSUE TITLE
Development Instructions

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqOnline#6]
I am lost on the current state for getting this working locally for development. The development instructions should be updated to the new Mux.jl setup, and then I'll take a few things off your plate if you don't get to them first (mostly adding `vars`. I will not be tweeting/sharing this until that option is available, along with the error handling and hopefully more responsiveness).

**Comment by amellnik** [comment]
The README in the other repo should be pretty accurate.  Splitting it in two is a pain, but since Heroku uses git for its revision tracking and such I don't know of any easy way to keep them together.  Basically

```
julia ./api/mux_server.jl 7777
```

starts the back end in that repo and 

```
ng serve
```

in this one should work. I'll clean up the deployment instructions for both.

**Comment by ChrisRackauckas** [comment]
I got it down. Thanks!
